# Generated by Django 4.2.7 on 2023-11-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('disponibilidad', models.BooleanField(default=True)),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
    ]
