# Generated by Django 4.2.7 on 2023-11-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_libro_cantidad_libro_cantidad_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], max_length=20),
        ),
    ]
