# Generated by Django 4.2.7 on 2023-11-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_libro_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='cantidad_total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], default='disponible', max_length=15),
        ),
    ]
