# Generated by Django 4.2.7 on 2023-11-08 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator()])),
                ('telefono', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('direccion', models.CharField(max_length=200)),
                ('multas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
